apply plugin: 'application'

dependencies {
    implementation libs.picocli, libs.night.config.toml

    implementation libs.log4j.core, libs.log4j.slf4j2

    implementation(libs.ical4j) {
        capabilities {
            requireCapability("org.mnode.ical4j:ical4j-filter-expressions")
        }
    }
}

jar {
    manifest {
        attributes(
                'Implementation-Title': 'iCal4j CLI',
                'Implementation-Version': version,
                'Implementation-Vendor': 'Ben Fortuna'
        )
    }
}

application {
    mainClass = 'org.ical4j.command.CommandMain'
}

startScripts {
    applicationName = 'ict'
    classpath = files('lib/*')
}
